--
-- PostgreSQL database dump
--

-- Dumped from database version 12.12
-- Dumped by pg_dump version 14.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AlbumComments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AlbumComments" (
    "Id" integer NOT NULL,
    "AuthorUserId" integer,
    "AlbumId" integer NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "Text" text
);


ALTER TABLE public."AlbumComments" OWNER TO postgres;

--
-- Name: AlbumComments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AlbumComments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AlbumComments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AlbumLocations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AlbumLocations" (
    "Id" integer NOT NULL,
    "AlbumId" integer NOT NULL,
    "LocationId" integer NOT NULL
);


ALTER TABLE public."AlbumLocations" OWNER TO postgres;

--
-- Name: AlbumLocations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AlbumLocations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AlbumLocations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Albums; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Albums" (
    "AlbumId" integer NOT NULL,
    "Name" text,
    "DateFrom" timestamp without time zone NOT NULL,
    "DateTo" timestamp without time zone NOT NULL,
    "DatePrecision" text
);


ALTER TABLE public."Albums" OWNER TO postgres;

--
-- Name: Albums_AlbumId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Albums" ALTER COLUMN "AlbumId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Albums_AlbumId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Locations" (
    "Id" integer NOT NULL,
    "Name" text,
    "Longitude" real NOT NULL,
    "Latitude" real NOT NULL,
    "LocationPrecisionMeters" integer NOT NULL,
    "Zoom" integer NOT NULL
);


ALTER TABLE public."Locations" OWNER TO postgres;

--
-- Name: Locations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Locations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Locations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PersonShot; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PersonShot" (
    "PersonsPersonId" integer NOT NULL,
    "ShotsShotId" integer NOT NULL
);


ALTER TABLE public."PersonShot" OWNER TO postgres;

--
-- Name: Persons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Persons" (
    "PersonId" integer NOT NULL,
    "FirstName" text,
    "LastName" text
);


ALTER TABLE public."Persons" OWNER TO postgres;

--
-- Name: Persons_PersonId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Persons" ALTER COLUMN "PersonId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Persons_PersonId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShotComments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ShotComments" (
    "Id" integer NOT NULL,
    "AuthorUserId" integer,
    "ShotId" integer NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "Text" text
);


ALTER TABLE public."ShotComments" OWNER TO postgres;

--
-- Name: ShotComments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ShotComments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShotComments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Shots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Shots" (
    "ShotId" integer NOT NULL,
    "Name" text,
    "AlbumId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Preview" bytea,
    "SourceUri" text,
    "LocationId" integer,
    "MD5" text,
    "ContentType" text
);


ALTER TABLE public."Shots" OWNER TO postgres;

--
-- Name: Shots_ShotId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Shots" ALTER COLUMN "ShotId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Shots_ShotId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "UserId" integer NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_UserId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "UserId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_UserId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: AlbumComments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AlbumComments" ("Id", "AuthorUserId", "AlbumId", "Timestamp", "Text") FROM stdin;
\.


--
-- Data for Name: AlbumLocations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AlbumLocations" ("Id", "AlbumId", "LocationId") FROM stdin;
\.


--
-- Data for Name: Albums; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Albums" ("AlbumId", "Name", "DateFrom", "DateTo", "DatePrecision") FROM stdin;
\.


--
-- Data for Name: Locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Locations" ("Id", "Name", "Longitude", "Latitude", "LocationPrecisionMeters", "Zoom") FROM stdin;
\.


--
-- Data for Name: PersonShot; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PersonShot" ("PersonsPersonId", "ShotsShotId") FROM stdin;
\.


--
-- Data for Name: Persons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Persons" ("PersonId", "FirstName", "LastName") FROM stdin;
\.


--
-- Data for Name: ShotComments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ShotComments" ("Id", "AuthorUserId", "ShotId", "Timestamp", "Text") FROM stdin;
\.


--
-- Data for Name: Shots; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Shots" ("ShotId", "Name", "AlbumId", "Date", "Preview", "SourceUri", "LocationId", "MD5", "ContentType") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("UserId") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20221018194601_init	6.0.5
\.


--
-- Name: AlbumComments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AlbumComments_Id_seq"', 1, false);


--
-- Name: AlbumLocations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AlbumLocations_Id_seq"', 1, false);


--
-- Name: Albums_AlbumId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Albums_AlbumId_seq"', 1, false);


--
-- Name: Locations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Locations_Id_seq"', 1, false);


--
-- Name: Persons_PersonId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Persons_PersonId_seq"', 1, false);


--
-- Name: ShotComments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ShotComments_Id_seq"', 1, false);


--
-- Name: Shots_ShotId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Shots_ShotId_seq"', 1, false);


--
-- Name: Users_UserId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_UserId_seq"', 1, false);


--
-- Name: AlbumComments PK_AlbumComments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AlbumComments"
    ADD CONSTRAINT "PK_AlbumComments" PRIMARY KEY ("Id");


--
-- Name: AlbumLocations PK_AlbumLocations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AlbumLocations"
    ADD CONSTRAINT "PK_AlbumLocations" PRIMARY KEY ("Id");


--
-- Name: Albums PK_Albums; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Albums"
    ADD CONSTRAINT "PK_Albums" PRIMARY KEY ("AlbumId");


--
-- Name: Locations PK_Locations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Locations"
    ADD CONSTRAINT "PK_Locations" PRIMARY KEY ("Id");


--
-- Name: PersonShot PK_PersonShot; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonShot"
    ADD CONSTRAINT "PK_PersonShot" PRIMARY KEY ("PersonsPersonId", "ShotsShotId");


--
-- Name: Persons PK_Persons; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Persons"
    ADD CONSTRAINT "PK_Persons" PRIMARY KEY ("PersonId");


--
-- Name: ShotComments PK_ShotComments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ShotComments"
    ADD CONSTRAINT "PK_ShotComments" PRIMARY KEY ("Id");


--
-- Name: Shots PK_Shots; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Shots"
    ADD CONSTRAINT "PK_Shots" PRIMARY KEY ("ShotId");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("UserId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_AlbumComments_AlbumId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AlbumComments_AlbumId" ON public."AlbumComments" USING btree ("AlbumId");


--
-- Name: IX_AlbumComments_AuthorUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AlbumComments_AuthorUserId" ON public."AlbumComments" USING btree ("AuthorUserId");


--
-- Name: IX_AlbumLocations_AlbumId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AlbumLocations_AlbumId" ON public."AlbumLocations" USING btree ("AlbumId");


--
-- Name: IX_AlbumLocations_LocationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AlbumLocations_LocationId" ON public."AlbumLocations" USING btree ("LocationId");


--
-- Name: IX_PersonShot_ShotsShotId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonShot_ShotsShotId" ON public."PersonShot" USING btree ("ShotsShotId");


--
-- Name: IX_ShotComments_AuthorUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ShotComments_AuthorUserId" ON public."ShotComments" USING btree ("AuthorUserId");


--
-- Name: IX_ShotComments_ShotId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ShotComments_ShotId" ON public."ShotComments" USING btree ("ShotId");


--
-- Name: IX_Shots_AlbumId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Shots_AlbumId" ON public."Shots" USING btree ("AlbumId");


--
-- Name: IX_Shots_LocationId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Shots_LocationId" ON public."Shots" USING btree ("LocationId");


--
-- Name: IX_Shots_MD5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Shots_MD5" ON public."Shots" USING btree ("MD5");


--
-- Name: AlbumComments FK_AlbumComments_Albums_AlbumId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AlbumComments"
    ADD CONSTRAINT "FK_AlbumComments_Albums_AlbumId" FOREIGN KEY ("AlbumId") REFERENCES public."Albums"("AlbumId") ON DELETE CASCADE;


--
-- Name: AlbumComments FK_AlbumComments_Users_AuthorUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AlbumComments"
    ADD CONSTRAINT "FK_AlbumComments_Users_AuthorUserId" FOREIGN KEY ("AuthorUserId") REFERENCES public."Users"("UserId");


--
-- Name: AlbumLocations FK_AlbumLocations_Albums_AlbumId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AlbumLocations"
    ADD CONSTRAINT "FK_AlbumLocations_Albums_AlbumId" FOREIGN KEY ("AlbumId") REFERENCES public."Albums"("AlbumId") ON DELETE CASCADE;


--
-- Name: AlbumLocations FK_AlbumLocations_Locations_LocationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AlbumLocations"
    ADD CONSTRAINT "FK_AlbumLocations_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES public."Locations"("Id") ON DELETE CASCADE;


--
-- Name: PersonShot FK_PersonShot_Persons_PersonsPersonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonShot"
    ADD CONSTRAINT "FK_PersonShot_Persons_PersonsPersonId" FOREIGN KEY ("PersonsPersonId") REFERENCES public."Persons"("PersonId") ON DELETE CASCADE;


--
-- Name: PersonShot FK_PersonShot_Shots_ShotsShotId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonShot"
    ADD CONSTRAINT "FK_PersonShot_Shots_ShotsShotId" FOREIGN KEY ("ShotsShotId") REFERENCES public."Shots"("ShotId") ON DELETE CASCADE;


--
-- Name: ShotComments FK_ShotComments_Shots_ShotId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ShotComments"
    ADD CONSTRAINT "FK_ShotComments_Shots_ShotId" FOREIGN KEY ("ShotId") REFERENCES public."Shots"("ShotId") ON DELETE CASCADE;


--
-- Name: ShotComments FK_ShotComments_Users_AuthorUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ShotComments"
    ADD CONSTRAINT "FK_ShotComments_Users_AuthorUserId" FOREIGN KEY ("AuthorUserId") REFERENCES public."Users"("UserId");


--
-- Name: Shots FK_Shots_Albums_AlbumId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Shots"
    ADD CONSTRAINT "FK_Shots_Albums_AlbumId" FOREIGN KEY ("AlbumId") REFERENCES public."Albums"("AlbumId") ON DELETE CASCADE;


--
-- Name: Shots FK_Shots_Locations_LocationId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Shots"
    ADD CONSTRAINT "FK_Shots_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES public."Locations"("Id");


--
-- PostgreSQL database dump complete
--

